# Generated by Django 5.2.17 on 2026-09-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_accountverification_id_alter_address_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdomain',
            options={'verbose_name': 'Subdomain', 'verbose_name_plural': 'Subdomains'},
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='slug',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, verbose_name='Subdomain'),
        ),
    ]
